### PR TITLE
Add Clockwork Finance Framework

### PR DESCRIPTION
**Pull request by webthethird**
I wasn't sure if the "EVM Bytecode" section was the right place to add this to the list, but since I saw several other papers listed there which are not directly related to bytecode, I figured it wouldn't hurt.

Credit to Kushal Babel (@kushalbabel), Phil Daian (@pdaian) and Mahimna Kelkar of Cornell University for the work.

### CODE REVIEW

**Comment by leonardoalt** [comment]
Thanks for the PR! We definitely should have Clockwork Finance in this list. Do you think it makes sense to have it in Specification instead of Bytecode?

**Comment by d-xo** [comment]
maybe an economic verification or game theory section or something?

**Comment by webthethird** [comment]
Sorry for the delayed response!

@leonardoalt I would tend to agree with @d-xo that an additional section might be useful. However, I also think putting it in the Specification section makes sense, especially since I think CFF would be the only work listed in a newly created Economics / Game Theory section. So I went ahead and moved it there for now!

**Review by leonardoalt — APPROVED** [review]
Thanks!

**Comment by leonardoalt** [comment]
@webthethird I'm fine with either option, even if the new section would have only one entry for now (I'm sure it will grow). So just let me know if you'd prefer me to merge as is or if you want to create the new section.

**Comment by d-xo** [comment]
I think we could already add open games to any econ / game theory section

**Comment by webthethird** [comment]
@leonardoalt @d-xo I'll move it to an Econ / Game Theory section then!

**Comment by webthethird** [comment]
@leonardoalt ready to merge :)

**Comment by leonardoalt** [comment]
Thanks again!

**Pull request merged**
